name: Full Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup EC2 & Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          # Install packages (first time only)
          sudo apt update
          sudo apt install python3-pip python3-venv git nginx -y

          # Clone or pull repo
          if [ ! -d "vinstagram" ]; then
            git clone https://github.com/Thriveni-9052/vinstagram.git
          fi

          cd vinstagram
          git pull origin main

          # Setup venv
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

          source venv/bin/activate
          pip install -r requirements.txt

          # Create Gunicorn service
          sudo bash -c 'cat > /etc/systemd/system/vinstagram.service <<EOF
          [Unit]
          Description=Gunicorn instance
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/vinstagram
          ExecStart=/home/ubuntu/vinstagram/venv/bin/gunicorn -w 3 -b 127.0.0.1:8000 app:app

          [Install]
          WantedBy=multi-user.target
          EOF'

          sudo systemctl daemon-reexec
          sudo systemctl enable vinstagram
          sudo systemctl restart vinstagram

          # Nginx config
          sudo bash -c 'cat > /etc/nginx/sites-available/vinstagram <<EOF
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://127.0.0.1:8000;
                  include proxy_params;
              }
          }
          EOF'
          sudo ln -sf /etc/nginx/sites-available/vinstagram /etc/nginx/sites-enabled
          sudo systemctl restart nginx

          
